<a href="https://colab.research.google.com/github/KA18202005/DeepLearning-Learning/blob/main/Keras_TUNER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [63]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [11]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8251 - loss: 0.3885 - val_accuracy: 0.8052 - val_loss: 0.4533
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7942 - loss: 0.4234 - val_accuracy: 0.8052 - val_loss: 0.4535
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8083 - loss: 0.4284 - val_accuracy: 0.8052 - val_loss: 0.4532
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4284 - val_accuracy: 0.8052 - val_loss: 0.4520
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8151 - loss: 0.4034 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8194 - loss: 0.3858 - val_accuracy: 0.8052 - val_loss: 0.4536
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8056 - loss: 0.4052 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.4052 - val_accuracy: 0.8117 - val_loss: 0.4533
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.4111 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3686 - val_accuracy: 0.8117 - val_loss: 0.4545
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7931 - loss: 0.4176 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8357 - loss: 0.3721 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8001 - loss: 0.4108 - val_accuracy: 0.8052 - val_loss: 0.4543
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8267 - loss: 0.3811 - val_accuracy: 0.8052 - val_loss: 0.4550
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4211 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8283 - loss: 0.3857 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8100 - loss: 0.4005 - val_accuracy: 0.8117 - val_loss: 0.4545
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8186 - loss: 0.3885 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4003 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8189 - loss: 0.3971 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8214 - loss: 0.4135 - val_accuracy: 0.7987 - val_loss: 0.4546
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8038 - loss: 0.4068 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8252 - loss: 0.3977 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.3913 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8050 - loss: 0.4067 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8092 - loss: 0.4211 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8294 - loss: 0.3766 - val_accuracy: 0.8052 - val_loss: 0.4548
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7901 - loss: 0.4296 - val_accuracy: 0.8052 - val_loss: 0.4568
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3945 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7976 - loss: 0.4193 - val_accuracy: 0.7987 - val_loss: 0.4547
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8255 - loss: 0.4053 - val_accuracy: 0.8052 - val_loss: 0.4566
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7881 - loss: 0.4442 - val_accuracy: 0.8052 - val_loss: 0.4554
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.4025 - val_accuracy: 0.8052 - val_loss: 0.4564
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8005 - loss: 0.4031 - val_accuracy: 0.8052 - val_loss: 0.4568
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8198 - loss: 0.3865 - val_accuracy: 0.8052 - val_loss: 0.4565
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8284 - loss: 0.4047 - val_accuracy: 0.8052 - val_loss: 0.4563
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8042 - loss: 0.4201 - val_accuracy: 0.8052 - val_loss: 0.4578
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8081 - loss: 0.3828 - val_accuracy: 0.8052 - val_loss: 0.4578
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8045 - loss: 0.3995 - val_accuracy: 0.8052 - val_loss: 0.4579
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8039 - loss: 0.4084 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8095 - loss: 0.4124 - val_accuracy: 0.8052 - val_loss: 0.4582
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8273 - loss: 0.3831 - val_accuracy: 0.8052 - val_loss: 0.4580
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8307 - loss: 0.3879 - val_accuracy: 0.8052 - val_loss: 0.4579
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8057 - loss: 0.4026 - val_accuracy: 0.8052 - val_loss: 0.4592
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8026 - loss: 0.4084 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8350 - loss: 0.3654 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8258 - loss: 0.3985 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7937 - loss: 0.4177 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8254 - loss: 0.3968 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7893 - loss: 0.4402 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8162 - loss: 0.4097 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8020 - loss: 0.4161 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8119 - loss: 0.3982 - val_accuracy: 0.8052 - val_loss: 0.4612
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8237 - loss: 0.3937 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7998 - loss: 0.4211 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8165 - loss: 0.4063 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3866 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8138 - loss: 0.4004 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.3877 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7925 - loss: 0.4379 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8268 - loss: 0.3931 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8224 - loss: 0.3805 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.3985 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8174 - loss: 0.4353 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8220 - loss: 0.3931 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8375 - loss: 0.3773 - val_accuracy: 0.8052 - val_loss: 0.4630
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8332 - loss: 0.3852 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8269 - loss: 0.3736 - val_accuracy: 0.8052 - val_loss: 0.4603
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8195 - loss: 0.4092 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7999 - loss: 0.4193 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8212 - loss: 0.3936 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8205 - loss: 0.3997 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8098 - loss: 0.4056 - val_accuracy: 0.7987 - val_loss: 0.4634
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7909 - loss: 0.4337 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8285 - loss: 0.3880 - val_accuracy: 0.7987 - val_loss: 0.4647
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8265 - loss: 0.3966 - val_accuracy: 0.7987 - val_loss: 0.4645
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8291 - loss: 0.3896 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8232 - loss: 0.4014 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8415 - loss: 0.3991 - val_accuracy: 0.8052 - val_loss: 0.4633
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8283 - loss: 0.3910 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8381 - loss: 0.3949 - val_accuracy: 0.8052 - val_loss: 0.4619
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.3994 - val_accuracy: 0.7922 - val_loss: 0.4631
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8114 - loss: 0.4034 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8141 - loss: 0.3966 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.3993 - val_accuracy: 0.8117 - val_loss: 0.4616
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8084 - loss: 0.4211 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8183 - loss: 0.4064 - val_accuracy: 0.7987 - val_loss: 0.4627
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8009 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7851 - loss: 0.4323 - val_accuracy: 0.8052 - val_loss: 0.4601
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8279 - loss: 0.3895 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3988 - val_accuracy: 0.7987 - val_loss: 0.4631
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8158 - loss: 0.4161 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.3955 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8425 - loss: 0.3718 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8356 - loss: 0.4035 - val_accuracy: 0.8052 - val_loss: 0.4660
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8258 - loss: 0.3897 - val_accuracy: 0.8052 - val_loss: 0.4649
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8269 - loss: 0.3939 - val_accuracy: 0.8052 - val_loss: 0.4640
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8270 - loss: 0.3954 - val_accuracy: 0.8052 - val_loss: 0.4647
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8328 - loss: 0.3801 - val_accuracy: 0.8052 - val_loss: 0.4647

# **KERAS TUNER**

In [15]:
!pip install keras-tuner
import keras_tuner as kt

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.1 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [24]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [25]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [26]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [27]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [28]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7275 - loss: 0.5857 - val_accuracy: 0.7987 - val_loss: 0.5623
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7685 - loss: 0.5579 - val_accuracy: 0.7987 - val_loss: 0.5531
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7598 - loss: 0.5477 - val_accuracy: 0.7922 - val_loss: 0.5458
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7202 - loss: 0.5757 - val_accuracy: 0.7987 - val_loss: 0.5382
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7708 - loss: 0.5280 - val_accuracy: 0.7922 - val_loss: 0.5316
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7299 - loss: 0.5442 - val_accuracy: 0.7922 - val_loss: 0.5256
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7375 - loss: 0.5289 - val_accuracy: 0.7922 - val_loss: 0.5201
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7624 - loss: 0.5162 - val_accuracy: 0.7922 - val_loss: 0.5150
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7581 - loss: 0.5180 - val_accuracy: 0.7987 - val_loss: 0.5105
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7934 - loss: 0.4896 - val_accuracy: 0.8052 - val_loss: 0.5067
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7673 - loss: 0.5047 - val_accuracy: 0.8052 - val_loss: 0.5034
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7675 - loss: 0.5036 - val_accuracy: 0.8117 - val_loss: 0.5001
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7485 - loss: 0.5070 - val_accuracy: 0.8052 - val_loss: 0.4979
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7472 - loss: 0.5083 - val_accuracy: 0.7922 - val_loss: 0.4950
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7505 - loss: 0.5096 - val_accuracy: 0.7987 - val_loss: 0.4929
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7426 - loss: 0.5115 - val_accuracy: 0.7987 - val_loss: 0.4907
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7678 - loss: 0.4882 - val_accuracy: 0.7922 - val_loss: 0.4885
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7614 - loss: 0.4984 - val_accuracy: 0.7922 - val_loss: 0.4864
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7636 - loss: 0.4910 - val_accuracy: 0.7922 - val_loss: 0.4845
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7609 - loss: 0.4813 - val_accuracy: 0.7922 - val_loss: 0.4831
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7800 - loss: 0.4720 - val_accuracy: 0.7922 - val_loss: 0.4817
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7856 - loss: 0.4726 - val_accuracy: 0.7922 - val_loss: 0.4802
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7952 - loss: 0.4664 - val_accuracy: 0.7987 - val_loss: 0.4790
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7383 - loss: 0.4970 - val_accuracy: 0.7987 - val_loss: 0.4776
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7750 - loss: 0.4744 - val_accuracy: 0.7987 - val_loss: 0.4765
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7651 - loss: 0.4709 - val_accuracy: 0.7987 - val_loss: 0.4754
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7648 - loss: 0.4798 - val_accuracy: 0.7987 - val_loss: 0.4746
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7651 - loss: 0.4842 - val_accuracy: 0.7922 - val_loss: 0.4737
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7730 - loss: 0.4792 - val_accuracy: 0.7922 - val_loss: 0.4729
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7496 - loss: 0.4760 - val_accuracy: 0.7922 - val_loss: 0.4721
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7813 - loss: 0.4675 - val_accuracy: 0.7857 - val_loss: 0.4717
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7812 - loss: 0.4631 - val_accuracy: 0.7857 - val_loss: 0.4710
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7684 - loss: 0.4680 - val_accuracy: 0.7857 - val_loss: 0.4704
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7738 - loss: 0.4777 - val_accuracy: 0.7857 - val_loss: 0.4699
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7778 - loss: 0.4526 - val_accuracy: 0.7922 - val_loss: 0.4696
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7713 - loss: 0.4725 - val_accuracy: 0.7922 - val_loss: 0.4695
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7413 - loss: 0.4974 - val_accuracy: 0.7922 - val_loss: 0.4691
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7823 - loss: 0.4627 - val_accuracy: 0.7922 - val_loss: 0.4688
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7790 - loss: 0.4696 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7959 - loss: 0.4393 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7570 - loss: 0.4710 - val_accuracy: 0.7987 - val_loss: 0.4674
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7954 - loss: 0.4642 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7667 - loss: 0.4739 - val_accuracy: 0.7987 - val_loss: 0.4665
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7551 - loss: 0.4853 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7831 - loss: 0.4529 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7880 - loss: 0.4485 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7635 - loss: 0.4626 - val_accuracy: 0.7922 - val_loss: 0.4658
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7542 - loss: 0.4734 - val_accuracy: 0.7922 - val_loss: 0.4653
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7820 - loss: 0.4545 - val_accuracy: 0.7922 - val_loss: 0.4650
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7616 - loss: 0.4692 - val_accuracy: 0.7922 - val_loss: 0.4647
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7729 - loss: 0.4643 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7724 - loss: 0.4620 - val_accuracy: 0.7922 - val_loss: 0.4639
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7885 - loss: 0.4552 - val_accuracy: 0.7922 - val_loss: 0.4638
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7747 - loss: 0.4661 - val_accuracy: 0.7922 - val_loss: 0.4634
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7891 - loss: 0.4614 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7919 - loss: 0.4593 - val_accuracy: 0.7987 - val_loss: 0.4628
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7703 - loss: 0.4519 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7977 - loss: 0.4382 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7729 - loss: 0.4549 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7778 - loss: 0.4507 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7924 - loss: 0.4316 - val_accuracy: 0.7987 - val_loss: 0.4621
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7691 - loss: 0.4672 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7689 - loss: 0.4705 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4605 - val_accuracy: 0.7987 - val_loss: 0.4618
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8102 - loss: 0.4140 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7843 - loss: 0.4357 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7910 - loss: 0.4343 - val_accuracy: 0.7987 - val_loss: 0.4617
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7575 - loss: 0.4747 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7716 - loss: 0.4728 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7541 - loss: 0.4785 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7918 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7692 - loss: 0.4513 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7935 - loss: 0.4494 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4521 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4679 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7642 - loss: 0.4564 - val_accuracy: 0.7987 - val_loss: 0.4602
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7795 - loss: 0.4497 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7689 - loss: 0.4580 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7819 - loss: 0.4414 - val_accuracy: 0.7987 - val_loss: 0.4599
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7908 - loss: 0.4363 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7670 - loss: 0.4582 - val_accuracy: 0.7987 - val_loss: 0.4597
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7681 - loss: 0.4645 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7748 - loss: 0.4381 - val_accuracy: 0.7987 - val_loss: 0.4593
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7754 - loss: 0.4498 - val_accuracy: 0.7987 - val_loss: 0.4595
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4547 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7794 - loss: 0.4528 - val_accuracy: 0.7987 - val_loss: 0.4594
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7707 - loss: 0.4551 - val_accuracy: 0.7987 - val_loss: 0.4592
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4601 - val_accuracy: 0.7987 - val_loss: 0.4592
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7651 - loss: 0.4499 - val_accuracy: 0.7987 - val_loss: 0.4590
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7828 - loss: 0.4436 - val_accuracy: 0.7987 - val_loss: 0.4589
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7811 - loss: 0.4476 - val_accuracy: 0.7987 - val_loss: 0.4587
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7555 - loss: 0.4864 - val_accuracy: 0.7987 - val_loss: 0.4586
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7767 - loss: 0.4443 - val_accuracy: 0.7987 - val_loss: 0.4585

In [40]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=8)
  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer = 'sgd', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [41]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5, directory='mydir', project_name='Kavya')

Reloading Tuner from mydir/Kavya/tuner0.json

In [42]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [43]:
tuner.get_best_hyperparameters()[0].values

{'units': 80}

In [44]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [45]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.6697 - loss: 0.6619 - val_accuracy: 0.7532 - val_loss: 0.6270
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6847 - loss: 0.6422 - val_accuracy: 0.7468 - val_loss: 0.6105
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6978 - loss: 0.6311 - val_accuracy: 0.7597 - val_loss: 0.5965
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6835 - loss: 0.6221 - val_accuracy: 0.7468 - val_loss: 0.5837
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6949 - loss: 0.6025 - val_accuracy: 0.7468 - val_loss: 0.5733
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7328 - loss: 0.5871 - val_accuracy: 0.7532 - val_loss: 0.5633
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7155 - loss: 0.5746 - val_accuracy: 0.7468 - val_loss: 0.5544
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7222 - loss: 0.5791 - val_accuracy: 0.7662 - val_loss: 0.5467
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7382 - loss: 0.5572 - val_accuracy: 0.7662 - val_loss: 0.5396
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7247 - loss: 0.5570 - val_accuracy: 0.7597 - val_loss: 0.5338
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7319 - loss: 0.5414 - val_accuracy: 0.7662 - val_loss: 0.5279
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7528 - loss: 0.5378 - val_accuracy: 0.7662 - val_loss: 0.5228
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7372 - loss: 0.5377 - val_accuracy: 0.7662 - val_loss: 0.5181
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7228 - loss: 0.5354 - val_accuracy: 0.7727 - val_loss: 0.5128
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7297 - loss: 0.5289 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7512 - loss: 0.5169 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7272 - loss: 0.5245 - val_accuracy: 0.7727 - val_loss: 0.5011
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7379 - loss: 0.5137 - val_accuracy: 0.7792 - val_loss: 0.4980
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7327 - loss: 0.5269 - val_accuracy: 0.7792 - val_loss: 0.4946
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5020 - val_accuracy: 0.7792 - val_loss: 0.4917
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7530 - loss: 0.5123 - val_accuracy: 0.7857 - val_loss: 0.4894
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7941 - loss: 0.4887 - val_accuracy: 0.7857 - val_loss: 0.4868
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7558 - loss: 0.5178 - val_accuracy: 0.7922 - val_loss: 0.4850
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7587 - loss: 0.5005 - val_accuracy: 0.7922 - val_loss: 0.4831
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7678 - loss: 0.4992 - val_accuracy: 0.7922 - val_loss: 0.4815
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7725 - loss: 0.4883 - val_accuracy: 0.7922 - val_loss: 0.4795
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7970 - loss: 0.4729 - val_accuracy: 0.7987 - val_loss: 0.4781
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7727 - loss: 0.4933 - val_accuracy: 0.7987 - val_loss: 0.4764
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7760 - loss: 0.4958 - val_accuracy: 0.7922 - val_loss: 0.4748
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7583 - loss: 0.5056 - val_accuracy: 0.7922 - val_loss: 0.4734
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7765 - loss: 0.4671 - val_accuracy: 0.7922 - val_loss: 0.4720
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4658 - val_accuracy: 0.7922 - val_loss: 0.4711
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7786 - loss: 0.4608 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7794 - loss: 0.4665 - val_accuracy: 0.7922 - val_loss: 0.4693
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4688 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7791 - loss: 0.4594 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7718 - loss: 0.4861 - val_accuracy: 0.7987 - val_loss: 0.4678
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7470 - loss: 0.4967 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8036 - loss: 0.4609 - val_accuracy: 0.7987 - val_loss: 0.4660
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7824 - loss: 0.4695 - val_accuracy: 0.8052 - val_loss: 0.4650
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7774 - loss: 0.4597 - val_accuracy: 0.8052 - val_loss: 0.4642
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7608 - loss: 0.5002 - val_accuracy: 0.8052 - val_loss: 0.4634
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7645 - loss: 0.4816 - val_accuracy: 0.8052 - val_loss: 0.4629
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7660 - loss: 0.4868 - val_accuracy: 0.8052 - val_loss: 0.4627
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.4609 - val_accuracy: 0.8052 - val_loss: 0.4625
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7811 - loss: 0.4797 - val_accuracy: 0.8052 - val_loss: 0.4619
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7892 - loss: 0.4604 - val_accuracy: 0.8052 - val_loss: 0.4616
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7894 - loss: 0.4512 - val_accuracy: 0.8052 - val_loss: 0.4614
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4605 - val_accuracy: 0.8052 - val_loss: 0.4610
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7797 - loss: 0.4582 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7930 - loss: 0.4738 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4602 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7922 - loss: 0.4401 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7731 - loss: 0.4781 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8030 - loss: 0.4411 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7702 - loss: 0.4681 - val_accuracy: 0.7987 - val_loss: 0.4598
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4453 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8073 - loss: 0.4466 - val_accuracy: 0.7987 - val_loss: 0.4598
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7761 - loss: 0.4586 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4373 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7792 - loss: 0.4546 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7888 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7802 - loss: 0.4612 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7806 - loss: 0.4501 - val_accuracy: 0.7987 - val_loss: 0.4601
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7926 - loss: 0.4377 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7856 - loss: 0.4588 - val_accuracy: 0.7922 - val_loss: 0.4595
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7564 - loss: 0.4676 - val_accuracy: 0.7922 - val_loss: 0.4592
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7641 - loss: 0.4745 - val_accuracy: 0.7922 - val_loss: 0.4591
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7893 - loss: 0.4411 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7658 - loss: 0.4718 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7585 - loss: 0.4756 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7814 - loss: 0.4539 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7746 - loss: 0.4499 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7870 - loss: 0.4569 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7795 - loss: 0.4513 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7743 - loss: 0.4739 - val_accuracy: 0.7922 - val_loss: 0.4587
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7835 - loss: 0.4372 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7879 - loss: 0.4360 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4592
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7853 - loss: 0.4408 - val_accuracy: 0.7922 - val_loss: 0.4588
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8137 - loss: 0.4133 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7905 - loss: 0.4412 - val_accuracy: 0.7922 - val_loss: 0.4585
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7621 - loss: 0.4547 - val_accuracy: 0.7922 - val_loss: 0.4583
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7717 - loss: 0.4606 - val_accuracy: 0.7922 - val_loss: 0.4581
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7728 - loss: 0.4608 - val_accuracy: 0.7922 - val_loss: 0.4578
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8037 - loss: 0.4081 - val_accuracy: 0.7922 - val_loss: 0.4576
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7838 - loss: 0.4460 - val_accuracy: 0.7922 - val_loss: 0.4577
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7685 - loss: 0.4476 - val_accuracy: 0.7922 - val_loss: 0.4576
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7918 - loss: 0.4257 - val_accuracy: 0.7857 - val_loss: 0.4574
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7831 - loss: 0.4496 - val_accuracy: 0.7857 - val_loss: 0.4577
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4499 - val_accuracy: 0.7857 - val_loss: 0.4581
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7688 - loss: 0.4549 - val_accuracy: 0.7857 - val_loss: 0.4577
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7540 - loss: 0.4715 - val_accuracy: 0.7857 - val_loss: 0.4577
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7691 - loss: 0.4601 - val_accuracy: 0.7857 - val_loss: 0.4579

In [47]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(80, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(80, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer = 'sgd', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [48]:
tuner = kt.RandomSearch(build_model, objective= 'val_accuracy', max_trials=3, directory='mydir', project_name='Kavya1')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [49]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.649350643157959
Total elapsed time: 00h 00m 09s

In [50]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [51]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [56]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, batch_size=32, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.7148 - loss: 0.6584 - val_accuracy: 0.6558 - val_loss: 0.6611
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6721 - loss: 0.6519 - val_accuracy: 0.6558 - val_loss: 0.6511
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6494 - loss: 0.6449 - val_accuracy: 0.6494 - val_loss: 0.6417
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6631 - loss: 0.6341 - val_accuracy: 0.6494 - val_loss: 0.6328
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6714 - loss: 0.6208 - val_accuracy: 0.6623 - val_loss: 0.6240
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6753 - loss: 0.6123 - val_accuracy: 0.6753 - val_loss: 0.6147
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7106 - loss: 0.5999 - val_accuracy: 0.6753 - val_loss: 0.6064
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6961 - loss: 0.5930 - val_accuracy: 0.6818 - val_loss: 0.5988
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7193 - loss: 0.5803 - val_accuracy: 0.6818 - val_loss: 0.5906
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7163 - loss: 0.5780 - val_accuracy: 0.7013 - val_loss: 0.5816
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7267 - loss: 0.5846 - val_accuracy: 0.7208 - val_loss: 0.5735
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7584 - loss: 0.5491 - val_accuracy: 0.7208 - val_loss: 0.5650
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7363 - loss: 0.5590 - val_accuracy: 0.7338 - val_loss: 0.5569
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7328 - loss: 0.5561 - val_accuracy: 0.7403 - val_loss: 0.5494
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7363 - loss: 0.5494 - val_accuracy: 0.7662 - val_loss: 0.5409
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7282 - loss: 0.5346 - val_accuracy: 0.7597 - val_loss: 0.5347
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7306 - loss: 0.5514 - val_accuracy: 0.7662 - val_loss: 0.5273
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5124 - val_accuracy: 0.7662 - val_loss: 0.5205
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7543 - loss: 0.5236 - val_accuracy: 0.7727 - val_loss: 0.5152
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7293 - loss: 0.5247 - val_accuracy: 0.7857 - val_loss: 0.5091
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7609 - loss: 0.4956 - val_accuracy: 0.7857 - val_loss: 0.5031
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7722 - loss: 0.5017 - val_accuracy: 0.7857 - val_loss: 0.4982
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7813 - loss: 0.4937 - val_accuracy: 0.7857 - val_loss: 0.4937
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7613 - loss: 0.4977 - val_accuracy: 0.7857 - val_loss: 0.4895
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7740 - loss: 0.4766 - val_accuracy: 0.7857 - val_loss: 0.4859
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7761 - loss: 0.4863 - val_accuracy: 0.7857 - val_loss: 0.4823
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4715 - val_accuracy: 0.7857 - val_loss: 0.4792
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7909 - loss: 0.4661 - val_accuracy: 0.7987 - val_loss: 0.4762
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4748 - val_accuracy: 0.8117 - val_loss: 0.4735
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7857 - loss: 0.4734 - val_accuracy: 0.8117 - val_loss: 0.4718
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4500 - val_accuracy: 0.8117 - val_loss: 0.4698
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7938 - loss: 0.4605 - val_accuracy: 0.8182 - val_loss: 0.4680
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7767 - loss: 0.4581 - val_accuracy: 0.8182 - val_loss: 0.4663
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7777 - loss: 0.4616 - val_accuracy: 0.8182 - val_loss: 0.4654
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7909 - loss: 0.4599 - val_accuracy: 0.8182 - val_loss: 0.4649
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4415 - val_accuracy: 0.8182 - val_loss: 0.4632
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8008 - loss: 0.4399 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7819 - loss: 0.4600 - val_accuracy: 0.8117 - val_loss: 0.4620
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7754 - loss: 0.4596 - val_accuracy: 0.8117 - val_loss: 0.4608
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7629 - loss: 0.4703 - val_accuracy: 0.8117 - val_loss: 0.4602
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7908 - loss: 0.4371 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7764 - loss: 0.4579 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7759 - loss: 0.4669 - val_accuracy: 0.8052 - val_loss: 0.4583
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7894 - loss: 0.4374 - val_accuracy: 0.8117 - val_loss: 0.4569
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7688 - loss: 0.4703 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7629 - loss: 0.4652 - val_accuracy: 0.8117 - val_loss: 0.4569
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7838 - loss: 0.4361 - val_accuracy: 0.8117 - val_loss: 0.4562
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7597 - loss: 0.4540 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7792 - loss: 0.4432 - val_accuracy: 0.8052 - val_loss: 0.4567
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7723 - loss: 0.4509 - val_accuracy: 0.8052 - val_loss: 0.4550
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4350 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8022 - loss: 0.4229 - val_accuracy: 0.8052 - val_loss: 0.4548
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7991 - loss: 0.4405 - val_accuracy: 0.8052 - val_loss: 0.4552
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4430 - val_accuracy: 0.8182 - val_loss: 0.4533
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7904 - loss: 0.4265 - val_accuracy: 0.8117 - val_loss: 0.4528
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7816 - loss: 0.4321 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8044 - loss: 0.4393 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7952 - loss: 0.4336 - val_accuracy: 0.8117 - val_loss: 0.4528
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4839 - val_accuracy: 0.8117 - val_loss: 0.4527
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7926 - loss: 0.4377 - val_accuracy: 0.8052 - val_loss: 0.4527
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7877 - loss: 0.4418 - val_accuracy: 0.8117 - val_loss: 0.4530
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7914 - loss: 0.4260 - val_accuracy: 0.8052 - val_loss: 0.4523
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4529 - val_accuracy: 0.8117 - val_loss: 0.4509
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7968 - loss: 0.4252 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7585 - loss: 0.4568 - val_accuracy: 0.8117 - val_loss: 0.4518
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7813 - loss: 0.4229 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7965 - loss: 0.4182 - val_accuracy: 0.7922 - val_loss: 0.4505
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4461 - val_accuracy: 0.8117 - val_loss: 0.4513
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7956 - loss: 0.4397 - val_accuracy: 0.8182 - val_loss: 0.4525
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7913 - loss: 0.4383 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7938 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7814 - loss: 0.4495 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8097 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4521
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7709 - loss: 0.4519 - val_accuracy: 0.8117 - val_loss: 0.4537
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7622 - loss: 0.4709 - val_accuracy: 0.8117 - val_loss: 0.4535
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7707 - loss: 0.4410 - val_accuracy: 0.8052 - val_loss: 0.4522
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7741 - loss: 0.4467 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7905 - loss: 0.4237 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7953 - loss: 0.4296 - val_accuracy: 0.7792 - val_loss: 0.4513
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7891 - loss: 0.4226 - val_accuracy: 0.7922 - val_loss: 0.4520
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7592 - loss: 0.4445 - val_accuracy: 0.7987 - val_loss: 0.4532
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7939 - loss: 0.4500 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8008 - loss: 0.4219 - val_accuracy: 0.7987 - val_loss: 0.4516
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7797 - loss: 0.4326 - val_accuracy: 0.8052 - val_loss: 0.4532
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7926 - loss: 0.4087 - val_accuracy: 0.8052 - val_loss: 0.4515
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4411 - val_accuracy: 0.8052 - val_loss: 0.4532
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8150 - loss: 0.4180 - val_accuracy: 0.7987 - val_loss: 0.4547
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7738 - loss: 0.4570 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7868 - loss: 0.4342 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7939 - loss: 0.4194 - val_accuracy: 0.8052 - val_loss: 0.4523
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7803 - loss: 0.4283 - val_accuracy: 0.7987 - val_loss: 0.4514
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4298 - val_accuracy: 0.8052 - val_loss: 0.4500
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7773 - loss: 0.4472 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8066 - loss: 0.4213 - val_accuracy: 0.8117 - val_loss: 0.4513

In [64]:
def build_model(hp):
  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
                      input_dim=8))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    else:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    counter +=1

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta', 'nadam']),
                loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [65]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='mydir', project_name='final1')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.6623376607894897

Best val_accuracy So Far: 0.6623376607894897
Total elapsed time: 00h 00m 15s

In [67]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 112,
 'activation0': 'sigmoid',
 'dropout0': 0.2,
 'optimizer': 'sgd',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.3,
 'units2': 72,
 'activation2': 'sigmoid',
 'dropout2': 0.5,
 'units3': 80,
 'activation3': 'sigmoid',
 'dropout3': 0.4,
 'units4': 128,
 'activation4': 'relu',
 'dropout4': 0.3,
 'units5': 104,
 'activation5': 'tanh',
 'dropout5': 0.2,
 'units6': 88,
 'activation6': 'sigmoid',
 'dropout6': 0.4,
 'units7': 16,
 'activation7': 'sigmoid',
 'dropout7': 0.2,
 'units8': 80,
 'activation8': 'sigmoid',
 'dropout8': 0.6}

In [68]:
model = tuner.get_best_models(num_models=1)[0]

In [69]:
model.fit(X_train, y_train, epochs=200, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6476 - loss: 0.6552 - val_accuracy: 0.6494 - val_loss: 0.6201
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6594 - loss: 0.6279 - val_accuracy: 0.6623 - val_loss: 0.6147
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6709 - loss: 0.6187 - val_accuracy: 0.6688 - val_loss: 0.6110
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6777 - loss: 0.6152 - val_accuracy: 0.6688 - val_loss: 0.6078
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.6746 - loss: 0.6193 - val_accuracy: 0.6623 - val_loss: 0.6059
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6511 - loss: 0.6148 - val_accuracy: 0.6623 - val_loss: 0.6031
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6474 - loss: 0.6228 - val_accuracy: 0.6558 - val_loss: 0.6019
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6026 - val_accuracy: 0.6818 - val_loss: 0.5957
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7096 - loss: 0.5989 - val_accuracy: 0.6883 - val_loss: 0.5931
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6576 - loss: 0.6078 - val_accuracy: 0.6818 - val_loss: 0.5906
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6748 - loss: 0.5977 - val_accuracy: 0.6818 - val_loss: 0.5878
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6703 - loss: 0.5937 - val_accuracy: 0.6948 - val_loss: 0.5853
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6866 - loss: 0.5949 - val_accuracy: 0.6818 - val_loss: 0.5836
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6944 - loss: 0.5959 - val_accuracy: 0.6883 - val_loss: 0.5805
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6972 - loss: 0.5593 - val_accuracy: 0.7143 - val_loss: 0.5779
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7120 - loss: 0.5777 - val_accuracy: 0.7143 - val_loss: 0.5756
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6956 - loss: 0.5722 - val_accuracy: 0.6883 - val_loss: 0.5734
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7113 - loss: 0.5789 - val_accuracy: 0.6948 - val_loss: 0.5713
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7267 - loss: 0.5481 - val_accuracy: 0.6883 - val_loss: 0.5695
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6738 - loss: 0.5760 - val_accuracy: 0.6883 - val_loss: 0.5689
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5946 - val_accuracy: 0.7143 - val_loss: 0.5648
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7207 - loss: 0.5689 - val_accuracy: 0.7143 - val_loss: 0.5628
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6803 - loss: 0.5919 - val_accuracy: 0.7013 - val_loss: 0.5626
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7077 - loss: 0.5676 - val_accuracy: 0.7078 - val_loss: 0.5596
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7028 - loss: 0.5699 - val_accuracy: 0.7078 - val_loss: 0.5575
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6977 - loss: 0.5644 - val_accuracy: 0.7143 - val_loss: 0.5553
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7309 - loss: 0.5466 - val_accuracy: 0.7143 - val_loss: 0.5539
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7001 - loss: 0.5824 - val_accuracy: 0.7143 - val_loss: 0.5521
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6945 - loss: 0.5489 - val_accuracy: 0.7273 - val_loss: 0.5503
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7174 - loss: 0.5455 - val_accuracy: 0.7338 - val_loss: 0.5483
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7285 - loss: 0.5523 - val_accuracy: 0.7273 - val_loss: 0.5468
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7007 - loss: 0.5600 - val_accuracy: 0.7597 - val_loss: 0.5454
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7099 - loss: 0.5540 - val_accuracy: 0.7273 - val_loss: 0.5440
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6969 - loss: 0.5830 - val_accuracy: 0.7078 - val_loss: 0.5444
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6980 - loss: 0.5470 - val_accuracy: 0.7078 - val_loss: 0.5432
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7385 - loss: 0.5186 - val_accuracy: 0.7597 - val_loss: 0.5398
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6916 - loss: 0.5701 - val_accuracy: 0.7338 - val_loss: 0.5395
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7178 - loss: 0.5560 - val_accuracy: 0.7338 - val_loss: 0.5386
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7286 - loss: 0.5490 - val_accuracy: 0.7468 - val_loss: 0.5363
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7156 - loss: 0.5552 - val_accuracy: 0.7468 - val_loss: 0.5353
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7383 - loss: 0.5488 - val_accuracy: 0.7792 - val_loss: 0.5332
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7182 - loss: 0.5442 - val_accuracy: 0.7597 - val_loss: 0.5323
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7400 - loss: 0.5132 - val_accuracy: 0.7597 - val_loss: 0.5310
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7021 - loss: 0.5511 - val_accuracy: 0.7468 - val_loss: 0.5308
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7227 - loss: 0.5505 - val_accuracy: 0.7468 - val_loss: 0.5306
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7299 - loss: 0.5551 - val_accuracy: 0.7468 - val_loss: 0.5302
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7131 - loss: 0.5337 - val_accuracy: 0.7468 - val_loss: 0.5283
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7297 - loss: 0.5294 - val_accuracy: 0.7792 - val_loss: 0.5256
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7050 - loss: 0.5623 - val_accuracy: 0.7792 - val_loss: 0.5246
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6840 - loss: 0.5668 - val_accuracy: 0.7662 - val_loss: 0.5240
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7627 - loss: 0.5225 - val_accuracy: 0.7597 - val_loss: 0.5238
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6977 - loss: 0.5708 - val_accuracy: 0.7468 - val_loss: 0.5244
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7425 - loss: 0.5287 - val_accuracy: 0.7597 - val_loss: 0.5225
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7100 - loss: 0.5662 - val_accuracy: 0.7727 - val_loss: 0.5208
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7107 - loss: 0.5439 - val_accuracy: 0.7662 - val_loss: 0.5204
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5551 - val_accuracy: 0.7468 - val_loss: 0.5210
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5134 - val_accuracy: 0.7792 - val_loss: 0.5178
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7429 - loss: 0.5181 - val_accuracy: 0.7727 - val_loss: 0.5166
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7434 - loss: 0.5197 - val_accuracy: 0.7727 - val_loss: 0.5170
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7221 - loss: 0.5238 - val_accuracy: 0.7727 - val_loss: 0.5161
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7333 - loss: 0.5562 - val_accuracy: 0.7792 - val_loss: 0.5151
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7186 - loss: 0.5380 - val_accuracy: 0.7792 - val_loss: 0.5141
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7433 - loss: 0.5170 - val_accuracy: 0.7727 - val_loss: 0.5129
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7503 - loss: 0.5155 - val_accuracy: 0.7727 - val_loss: 0.5122
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7200 - loss: 0.5295 - val_accuracy: 0.7597 - val_loss: 0.5111
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7139 - loss: 0.5413 - val_accuracy: 0.7727 - val_loss: 0.5106
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7332 - loss: 0.5362 - val_accuracy: 0.7727 - val_loss: 0.5122
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.5832 - val_accuracy: 0.7662 - val_loss: 0.5132
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7214 - loss: 0.5393 - val_accuracy: 0.7597 - val_loss: 0.5129
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7226 - loss: 0.5559 - val_accuracy: 0.7727 - val_loss: 0.5099
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7035 - loss: 0.5459 - val_accuracy: 0.7727 - val_loss: 0.5082
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7415 - loss: 0.5165 - val_accuracy: 0.7727 - val_loss: 0.5080
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7403 - loss: 0.5106 - val_accuracy: 0.7727 - val_loss: 0.5070
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5111 - val_accuracy: 0.7727 - val_loss: 0.5061
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7399 - loss: 0.5271 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7207 - loss: 0.5497 - val_accuracy: 0.7662 - val_loss: 0.5044
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7349 - loss: 0.5223 - val_accuracy: 0.7727 - val_loss: 0.5040
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7288 - loss: 0.5132 - val_accuracy: 0.7727 - val_loss: 0.5038
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7422 - loss: 0.5359 - val_accuracy: 0.7727 - val_loss: 0.5032
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7369 - loss: 0.5197 - val_accuracy: 0.7727 - val_loss: 0.5027
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7369 - loss: 0.5107 - val_accuracy: 0.7727 - val_loss: 0.5021
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7444 - loss: 0.5263 - val_accuracy: 0.7662 - val_loss: 0.5013
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7650 - loss: 0.4964 - val_accuracy: 0.7792 - val_loss: 0.5011
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7618 - loss: 0.4981 - val_accuracy: 0.7727 - val_loss: 0.5021
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7474 - loss: 0.5187 - val_accuracy: 0.7727 - val_loss: 0.5008
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7409 - loss: 0.5249 - val_accuracy: 0.7727 - val_loss: 0.5003
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7051 - loss: 0.5354 - val_accuracy: 0.7792 - val_loss: 0.4997
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7552 - loss: 0.5125 - val_accuracy: 0.7727 - val_loss: 0.5004
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7294 - loss: 0.5311 - val_accuracy: 0.7727 - val_loss: 0.5007
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7340 - loss: 0.5100 - val_accuracy: 0.7727 - val_loss: 0.4994
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5183 - val_accuracy: 0.7727 - val_loss: 0.5002
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7513 - loss: 0.5082 - val_accuracy: 0.7792 - val_loss: 0.4983
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7453 - loss: 0.5097 - val_accuracy: 0.7792 - val_loss: 0.4981
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7553 - loss: 0.5111 - val_accuracy: 0.7792 - val_loss: 0.4973
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5324 - val_accuracy: 0.7727 - val_loss: 0.4981
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7391 - loss: 0.5115 - val_accuracy: 0.7792 - val_loss: 0.4969
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7585 - loss: 0.4887 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7458 - loss: 0.5286 - val_accuracy: 0.7727 - val_loss: 0.4953
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7379 - loss: 0.5253 - val_accuracy: 0.7792 - val_loss: 0.4956
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7127 - loss: 0.5295 - val_accuracy: 0.7727 - val_loss: 0.4946
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7783 - loss: 0.4709 - val_accuracy: 0.7662 - val_loss: 0.4942
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7449 - loss: 0.5104 - val_accuracy: 0.7727 - val_loss: 0.4941
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7439 - loss: 0.5191 - val_accuracy: 0.7662 - val_loss: 0.4932
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7423 - loss: 0.5017 - val_accuracy: 0.7662 - val_loss: 0.4928
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5093 - val_accuracy: 0.7662 - val_loss: 0.4927
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7224 - loss: 0.5691 - val_accuracy: 0.7662 - val_loss: 0.4925
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7585 - loss: 0.4955 - val_accuracy: 0.7662 - val_loss: 0.4919
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7292 - loss: 0.5236 - val_accuracy: 0.7792 - val_loss: 0.4942
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7621 - loss: 0.4864 - val_accuracy: 0.7662 - val_loss: 0.4915
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7529 - loss: 0.5137 - val_accuracy: 0.7662 - val_loss: 0.4912
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7914 - loss: 0.4697 - val_accuracy: 0.7662 - val_loss: 0.4909
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7560 - loss: 0.5137 - val_accuracy: 0.7662 - val_loss: 0.4906
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7477 - loss: 0.5203 - val_accuracy: 0.7727 - val_loss: 0.4912
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7639 - loss: 0.5160 - val_accuracy: 0.7792 - val_loss: 0.4924
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7594 - loss: 0.4928 - val_accuracy: 0.7792 - val_loss: 0.4919
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7488 - loss: 0.5171 - val_accuracy: 0.7662 - val_loss: 0.4897
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7343 - loss: 0.5033 - val_accuracy: 0.7662 - val_loss: 0.4898
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7697 - loss: 0.4947 - val_accuracy: 0.7792 - val_loss: 0.4916
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7471 - loss: 0.5007 - val_accuracy: 0.7727 - val_loss: 0.4898
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7418 - loss: 0.5316 - val_accuracy: 0.7662 - val_loss: 0.4890
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7377 - loss: 0.5252 - val_accuracy: 0.7792 - val_loss: 0.4913
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7423 - loss: 0.5203 - val_accuracy: 0.7792 - val_loss: 0.4897
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7346 - loss: 0.5242 - val_accuracy: 0.7792 - val_loss: 0.4898
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7375 - loss: 0.5041 - val_accuracy: 0.7727 - val_loss: 0.4893
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7609 - loss: 0.4949 - val_accuracy: 0.7662 - val_loss: 0.4881
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7652 - loss: 0.5011 - val_accuracy: 0.7662 - val_loss: 0.4879
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7203 - loss: 0.5145 - val_accuracy: 0.7727 - val_loss: 0.4889
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7449 - loss: 0.5154 - val_accuracy: 0.7727 - val_loss: 0.4910
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7676 - loss: 0.4831 - val_accuracy: 0.7792 - val_loss: 0.4892
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7714 - loss: 0.4776 - val_accuracy: 0.7792 - val_loss: 0.4885
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5135 - val_accuracy: 0.7662 - val_loss: 0.4866
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7287 - loss: 0.5424 - val_accuracy: 0.7662 - val_loss: 0.4865
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7588 - loss: 0.5210 - val_accuracy: 0.7792 - val_loss: 0.4890
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7225 - loss: 0.5400 - val_accuracy: 0.7662 - val_loss: 0.4860
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7340 - loss: 0.5229 - val_accuracy: 0.7662 - val_loss: 0.4861
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7318 - loss: 0.5474 - val_accuracy: 0.7727 - val_loss: 0.4865
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7069 - loss: 0.5332 - val_accuracy: 0.7792 - val_loss: 0.4883
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7503 - loss: 0.4915 - val_accuracy: 0.7727 - val_loss: 0.4863
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7744 - loss: 0.4965 - val_accuracy: 0.7792 - val_loss: 0.4875
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7503 - loss: 0.5141 - val_accuracy: 0.7727 - val_loss: 0.4898
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7706 - loss: 0.4945 - val_accuracy: 0.7727 - val_loss: 0.4864
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7633 - loss: 0.5022 - val_accuracy: 0.7727 - val_loss: 0.4854
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7572 - loss: 0.5075 - val_accuracy: 0.7792 - val_loss: 0.4870
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5267 - val_accuracy: 0.7727 - val_loss: 0.4874
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7924 - loss: 0.4700 - val_accuracy: 0.7727 - val_loss: 0.4871
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7619 - loss: 0.5317 - val_accuracy: 0.7727 - val_loss: 0.4877
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7563 - loss: 0.5222 - val_accuracy: 0.7727 - val_loss: 0.4856
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7355 - loss: 0.5290 - val_accuracy: 0.7727 - val_loss: 0.4857
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7351 - loss: 0.5145 - val_accuracy: 0.7727 - val_loss: 0.4843
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7523 - loss: 0.5054 - val_accuracy: 0.7662 - val_loss: 0.4835
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7391 - loss: 0.5274 - val_accuracy: 0.7727 - val_loss: 0.4839
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7503 - loss: 0.4933 - val_accuracy: 0.7727 - val_loss: 0.4840
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7341 - loss: 0.5193 - val_accuracy: 0.7727 - val_loss: 0.4844
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7759 - loss: 0.4800 - val_accuracy: 0.7662 - val_loss: 0.4833
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7695 - loss: 0.5023 - val_accuracy: 0.7727 - val_loss: 0.4840
Epoch 161/200